/**
 * THE EVENT BUS.
 *
 * `EventName` is generated by hand from docs/03-event-taxonomy.md and is a closed union, so an
 * invented event name is a COMPILE ERROR rather than a silent analytics hole. That is what makes
 * the taxonomy a contract instead of a suggestion.
 *
 * track() auto-merges every global property, so no call site can forget `coins_short_by` — the
 * one property that separates a pricing failure from an interest failure.
 */

export type EventName =
  // discovery
  | 'store_tile_impression' | 'store_opened' | 'sku_impression' | 'sku_view'
  // intent
  | 'coin_slider_moved' | 'goal_created' | 'goal_progressed' | 'goal_completed' | 'goal_abandoned'
  // conversion
  | 'checkout_started' | 'coin_applied' | 'payment_success' | 'voucher_delivered'
  // trust layer
  | 'vault_viewed' | 'goals_viewed' | 'ledger_viewed' | 'voucher_expired_coins_refunded'
  // observable ONLY via a brand-side webhook. Never fired by this prototype.
  | 'voucher_redeemed'

/** Funnel position, or null for off-funnel events. Drives the PM panel funnel. */
export const FUNNEL: EventName[] = [
  'store_tile_impression', 'store_opened', 'sku_view',
  'goal_created', 'checkout_started', 'payment_success',
]

/** The step we instrument for. sku_view -> goal_created. See 03-event-taxonomy.md. */
export const LEAK_STEP = { from: 'sku_view', to: 'goal_created' } as const

export interface TrackedEvent {
  seq: number
  name: EventName
  ts: number
  props: Record<string, unknown>
}

type ContextFn = () => Record<string, unknown>
let getContext: ContextFn = () => ({})
/** The store registers itself here, so events.ts never imports the store (no cycle). */
export const registerContext = (fn: ContextFn) => { getContext = fn }

const CAP = 500
let seq = 0
let log: TrackedEvent[] = []
const listeners = new Set<() => void>()

const KEY = 'pr_events'
try {
  const raw = localStorage.getItem(KEY)
  if (raw) { log = JSON.parse(raw); seq = log.length ? log[0].seq : 0 }
} catch { /* private mode, cleared storage, or a blocked accessor */ }

const flush = () => {
  try { localStorage.setItem(KEY, JSON.stringify(log.slice(0, 120))) } catch { /* ignore */ }
  listeners.forEach(l => l())
}

export function track(name: EventName, props: Record<string, unknown> = {}) {
  const e: TrackedEvent = { seq: ++seq, name, ts: Date.now(), props: { ...getContext(), ...props } }
  log = [e, ...log].slice(0, CAP)   // newest first
  flush()
}

export const getLog = () => log
export const clearLog = () => { log = []; seq = 0; flush() }
export const subscribe = (fn: () => void) => { listeners.add(fn); return () => { listeners.delete(fn) } }

/** Count of a given event in the log — the funnel's raw material. */
export const countOf = (name: EventName) => log.reduce((n, e) => n + (e.name === name ? 1 : 0), 0)

/** Distribution of coins_short_by at the leak, so the panel shows WHY it leaks. */
export function shortByDistribution() {
  const vals = log
    .filter(e => e.name === 'sku_view')
    .map(e => Number(e.props.coins_short_by ?? 0))
  const bucket = { zero: 0, near: 0, far: 0 }
  for (const v of vals) {
    if (v === 0) bucket.zero++
    else if (v <= 1500) bucket.near++
    else bucket.far++
  }
  return { ...bucket, total: vals.length }
}
